language: java

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "mleyb-github"
    token:
      secure: "$SONAR_TOKEN"

before_install:
 - chmod +x gradlew

script:
  - sonar-scanner
  - ./gradlew check
  - ./gradlew build